name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          scp -i keyfile -r -o StrictHostKeyChecking=no ./build/* root@agoregontrail.org:/var/www/site/build
          ssh -i keyfile -o StrictHostKeyChecking=no root@agoregontrail.org '
            sudo systemctl restart nginx
            # Add any other commands you need to run on the server
          '
          rm keyfile

      - run: echo "🍏 This job's status is ${{ job.status }}."