name: Deploy Oregon Trail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and build frontend
        run: |
          cd oregontrail
          npm ci
          npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Backend deployment
            cd /var/www/site/Server
            git pull origin main
            npm ci
            pm2 restart oregontrailServer.js || pm2 start oregontrailServer.js
            
            # Frontend deployment
            rm -rf /var/www/site/build/*
            cp -r /var/www/site/oregontrail/build/* /var/www/site/build/
            
            # Reload Nginx
            sudo systemctl reload nginx

      - name: Copy frontend build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "oregontrail/build/*"
          target: "/var/www/site/oregontrail/build"
          strip_components: 2